name: Validation

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  validate_homeworks:
    runs-on: ubuntu-latest
    name: Validate all homeworks

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install root dependencies
        run: pip install -r requirements.txt

      - name: Build & install custom_json
        working-directory: ./10
        run: |
          pip install -r ../requirements.txt
          pip install -e .

      - name: Check flake8
        working-directory: ./10
        run: flake8 .

      - name: Check pylint
        working-directory: ./10
        run: pylint setup.py test_correct.py test_perf.py

      - name: Run pytest + coverage
        working-directory: ./10
        run: |
          coverage run -m pytest .
          coverage report -m
